In [1]:
import numpy as np

In [4]:
a = np.arange(1,15,2)
print(a)

[ 1  3  5  7  9 11 13]


In [14]:
#sqrt
b = np.sqrt(a)

In [12]:
np.exp(a)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05])

In [17]:
np.add(a,b)

array([ 2.        ,  4.73205081,  7.23606798,  9.64575131, 12.        ,
       14.31662479, 16.60555128])

### Conditional Clause and Boolean Operation

In [23]:
x = np.array([100,400,500,600]) # let each data item be 'a'
y = np.array([10,15,20,25]) # let each data item be 'b'

condition = np.array([True, True, False, False])

In [21]:
# use loop indirectly to perform this
z = [a if cond else b for a, cond, b in zip(x, condition,y)]

In [24]:
print(z)

[100, 400, 20, 25]


In [28]:
# np.where(condition, value-for-yes, value-for-no)
z2 = np.where(condition, x, y)

In [29]:
print(z2)

[100 400  20  25]


In [31]:
# Standard function
z2.sum()

545

In [33]:
#Sum column

n = np.array([[1,2],[3,4]])