# Vector, matrices and multidimentional arrays

In [1]:
import numpy as np

In [4]:
a = np.arange(1,15,2)
print(a)

[ 1  3  5  7  9 11 13]


In [14]:
#sqrt
b = np.sqrt(a)

In [12]:
np.exp(a)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05])

In [17]:
np.add(a,b)

array([ 2.        ,  4.73205081,  7.23606798,  9.64575131, 12.        ,
       14.31662479, 16.60555128])

### Conditional Clause and Boolean Operation

In [23]:
x = np.array([100,400,500,600]) # let each data item be 'a'
y = np.array([10,15,20,25]) # let each data item be 'b'

condition = np.array([True, True, False, False])

In [21]:
# use loop indirectly to perform this
z = [a if cond else b for a, cond, b in zip(x, condition,y)]

In [24]:
print(z)

[100, 400, 20, 25]


In [28]:
# np.where(condition, value-for-yes, value-for-no)
z2 = np.where(condition, x, y)

In [29]:
print(z2)

[100 400  20  25]


In [31]:
# Standard function
z2.sum()

545

In [36]:
#Sum column

n = np.array([[1,2],[3,4]])
print(n)

[[1 2]
 [3 4]]


In [38]:
# column sum
print(n.sum(0))

[4 6]


In [40]:
# row sum
print(n.sum(1))

[3 7]


In [42]:
print(n.mean())
print(n.std())
print(n.var())

2.5
1.118033988749895
1.25


In [44]:
condition2 = np.array([True, False, True])

In [49]:
# condition2.any() # or operator
condition2.all() # and operator

False

In [66]:
array2 = np.array(['solid', 'solid', 'liquid', 'solid', 'liquid'])

In [70]:
print(np.unique(array2))

['liquid' 'solid']


In [72]:
# Sorting in numpy array
unsorted = np.array([1,2,8,10,7,9,4])

In [75]:
sorted_array = np.sort(unsorted)

In [77]:
print(sorted_array)

[ 1  2  4  7  8  9 10]


## 2. Data Manipulation with Pandas

In [79]:
import pandas as pd
from pandas import Series

In [81]:
obj1 = Series([5,10,15,20])

In [83]:
print(obj1)

0     5
1    10
2    15
3    20
dtype: int64


In [94]:
#use numpy array to series
data_array = np.array(['a', 'b', 'c'])

s = Series(data_array)

In [97]:
# custom index
s = Series(data_array, index=[100,101,102])
print(s)

100    a
101    b
102    c
dtype: object


In [113]:
revenue = Series([20,80,40,35], index=['ola', 'uber', 'grab','goje'])
print(revenue)
# print(revenue['ola'])
# print(revenue[revenue>=34])

ola     20
uber    80
grab    40
goje    35
dtype: int64


In [104]:
revenue_dict = revenue.to_dict()
print(revenue_dict)
print(type(revenue_dict))

{'ola': 20, 'uber': 80, 'grab': 40, 'goje': 35}
<class 'dict'>


In [111]:
index2 = ['musa', 'saleh', 'isa', 'modu', 'tanko']
revenue2 = Series(revenue, index2)
# print(revenue2)
pd.isnull(revenue2)

musa     True
saleh    True
isa      True
modu     True
tanko    True
dtype: bool

In [112]:
print(revenue + revenue2)

goje    NaN
grab    NaN
isa     NaN
modu    NaN
musa    NaN
ola     NaN
saleh   NaN
tanko   NaN
uber    NaN
dtype: float64
